• To - Do - 1:
1. Read and Observe the Dataset.
2. Print top(5) and bottom(5) of the dataset {Hint: pd.head and pd.tail}.
3. Print the Information of Datasets. {Hint: pd.info}.
4. Gather the Descriptive info about the Dataset. {Hint: pd.describe}
5. Split your data into Feature (X) and Label (Y).*italicized text*

In [16]:
import pandas as pd

# 1. Read and Observe the Dataset
data = pd.read_csv('/content/drive/MyDrive/WEEK5/student.csv')
data






Math  Reading  Writing
0      48       68       63
1      62       81       72
2      79       80       78
3      76       83       79
4      59       64       62
..    ...      ...      ...
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

[1000 rows x 3 columns]

In [8]:
# 2. Print top(5) and bottom(5) of the dataset

data.head()


Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

In [9]:
data.tail()

Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

In [10]:

# 3. Print the Information of Datasets
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     1000 non-null   int64
 1   Reading  1000 non-null   int64
 2   Writing  1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB


In [11]:


# 4. Gather the Descriptive info about the Dataset
data.describe()

Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60.750000    58.000000
50%      68.000000    70.000000    69.500000
75%      78.000000    81.000000    79.000000
max     100.000000   100.000000   100.000000

In [15]:

# 5. Split your data into Feature (X) and Label (Y)
# Assuming 'Math_score' is the label and the rest are features
X = data.drop('Math', axis=1)  # Features
Y = data['Math']  # Label
print("Features (X):")
print(X.head())

print("\nLabel (Y):")
print(Y.head())

Features (X):
   Reading  Writing
0       68       63
1       81       72
2       80       78
3       83       79
4       64       62

Label (Y):
0    48
1    62
2    79
3    76
4    59
Name: Math, dtype: int64


**• To - Do - 2:**
1. To make the task easier - let’s assume there is no bias or intercept.
2. Create the following matrices:

Y = WTX[link text](https://)

In [18]:
import numpy as np

# Extract features and label
X = data.drop('Math', axis=1).values.T  # Transpose to match shape (d x n)
Y_actual = data['Math'].values  # Actual labels

# Initialize weight matrix (random values for illustration)
d = X.shape[0]  # Number of features
W = np.random.rand(d, 1)  # Weight vector of shape (d x 1)

# Compute predicted Y (Y = W^T X)
Y_pred = np.dot(W.T, X)  # Shape: (1 x n)

# Print the matrices
print("Feature Matrix (X):")
print(X[:, :5])  # Display first 5 samples

print("\nWeight Matrix (W):")
print(W)

print("\nPredicted Label Vector (Y):")
print(Y_pred[:, :5])  # Display predictions for first 5 samples

Feature Matrix (X):
[[68 81 80 83 64]
 [63 72 78 79 62]]

Weight Matrix (W):
[[0.3298291 ]
 [0.55893705]]

Predicted Label Vector (Y):
[[57.64141304 66.95962481 69.983418   71.53184236 55.76315958]]


### **• To - Do - 3:**

1. Split the dataset into training and test sets.
2. You can use an 80-20 or 70-30 split, with 80% (or 70%) of the data used for training and the rest
for testing.

In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Assuming the dataset is loaded into a Pandas DataFrame called 'data'
# If the dataset is in CSV format, load it like this:
# data = pd.read_csv('your_dataset.csv')

# Example dataset (replace with your actual dataset)
# Assume the dataset has 'X' as features and 'Y' as the target variable.
X = data.drop(columns=['Math'])
y = data['Math']

# Splitting the dataset into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Check the shapes of the training and testing sets
print(f"Training features shape: {X_train.shape}")
print(f"Training labels shape: {y_train.shape}")
print(f"Testing features shape: {X_test.shape}")
print(f"Testing labels shape: {y_test.shape}")


Training features shape: (800, 2)
Training labels shape: (800,)
Testing features shape: (200, 2)
Testing labels shape: (200,)


# **• To - Do:4**
We will define a function that:
1. Loads the data and splits it into training and test sets.
2. Prepares the feature matrix (X) and target vector (Y).
3. Defines the weight matrix (W) and initializes the learning rate and number of iterations.
4. Calls the gradient descent function to learn the parameters.
5. Evaluates the model using RMSE and R2
.


In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler # Import StandardScaler for feature scaling


data = pd.read_csv('/content/drive/MyDrive/WEEK5/student.csv')

# Step 1: Load data and split into train and test sets
X = data.drop('Writing', axis=1)
y = data['Writing']

# Split data into training and testing (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 2: Feature Scaling using Standardization
scaler = StandardScaler() # Create a StandardScaler object
X_train = scaler.fit_transform(X_train) # Fit and transform on training data
X_test = scaler.transform(X_test) # Transform test data using the same scaler

# Step 3: Initialize weight matrix (W), learning rate, and number of iterations
m, n = X_train.shape  # m is number of training samples, n is number of features
W = np.random.randn(n)  # Random initialization of weights
learning_rate = 0.01
iterations = 1000

# Step 4: Gradient Descent function
def gradient_descent(X, y, W, learning_rate, iterations):
    m = len(y)
    for i in range(iterations):
        predictions = X.dot(W)
        errors = predictions - y
        gradients = (2/m) * X.T.dot(errors)  # Compute gradients
        W -= learning_rate * gradients  # Update weights
    return W

# Train the model using gradient descent
W_optimal = gradient_descent(X_train, y_train, W, learning_rate, iterations)

# Step 5: Evaluate the model

# Make predictions
y_pred = X_test.dot(W_optimal)

# RMSE (Root Mean Squared Error)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

# R² (R-squared) score
r2 = r2_score(y_test, y_pred)

print(f'Optimal Weights: {W_optimal}')
print(f'RMSE: {rmse}')
print(f'R²: {r2}')

Optimal Weights: [ 1.44502057 13.20423401]
RMSE: 69.12066137053911
R²: -18.80091530020187
